# -*- coding: utf-8 -*-
#
# author: Roc Granada Verdú
# All the problems on github: https://github.com/Hoter11/Project-Euler
#
#
# Even Fibonacci numbers:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci(maximum,x=1,y=2,result=0):
    """Fibonacci funcion that sums the even values until the maximum value specified"""
    if x >= maximum: return result
    if x % 2 == 0: result += x
    return fibonacci(maximum,y,x+y,result)

print fibonacci(4000000)
